### ISSUE TITLE
Offenses detected for GraphQL/MaxComplexitySchema and GraphQL/MaxDepthSchema when defined in subclass

### ISSUE THREAD

**Issue by McRip** [DmitryTsepelev/rubocop-graphql#133]
In the following case, if max_depth and max_complexity are defined in a subclass (or even in an include of a subclass), offenses will be detected for the corresponding cops.

Using Classic Autoloader.

Thanks in advance

```
class GraphqlSchema < Graphql::BaseSchema
  ...
end

module Graphql
  class BaseSchema < ::GraphQL::Schema
    include ::Graphql::Concerns::BaseSchema
  end
end

module Graphql
  module Concerns
    module BaseSchema
      extend ActiveSupport::Concern

      included do
        max_depth(...)
        max_complexity(...)
        default_max_page_size(...)
      end
    end
  end
end
```

**Comment by DmitryTsepelev** [comment]
Hey! Fixed in [1.1.1](https://github.com/DmitryTsepelev/rubocop-graphql/blob/master/CHANGELOG.md#111-2023-04-01), LMK if it didn't help

**Comment by McRip** [comment]
Sorry, forgot to mention that we are on 1.1.1. Issue still present.

**Comment by DmitryTsepelev** [comment]
Ah got it. The problem is that it will be a bit hard and error–prone to check all included modules for `max_depth` and all the related staff 😞

I'd suggest to do the following:
1. Disable the cop
2. Add your own cop to the codebase that will check that each class that inherits from `GraphQL::Schema` has `BaseSchema` included
